### ISSUE TITLE
Separate repos for M1/M2

### ISSUE THREAD

**Issue by sdesmet** [what3words/magento-w3w-plugin#2]
Hi,

Would be great if you could put the modules in _separate_ repositories so at least we could use composer to pull them down. The way you've set it up now just doesn't allow us to do something like this:

```js
{
    "name": "acme/test",
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/what3words/magento-w3w-plugin.git"
        }
    ],
    "require": {
        "what3words/module-what3words": "^1.0"
    }
}
```

Or, publish them on [Magento Marketplace](https://marketplace.magento.com) so, again we can pull the code out of a proxy, like repo.magento.com and automatically get updates.

Or, publish them on [Packagist](https://packagist.org), totally free service to proxy your PHP code and allow your package users to immediately subscribe to updates. You already using it for `what3words/w3w-php-wrapper`, so why _not_ for this module?

As per your README: 
> download the plugin

Seriously, it's 2018, the PHP world and Magento 2 has embraced composer, you should too.

Thanks,
Steve

**Comment by lemaryn** [comment]
Hi guys! I support sdesmet's proposal. 
Could you do it please?
Regards,
Serhii

**Comment by andycurriew3w** [comment]
Thanks for your feedback. We've now split them out into their own repos and added a note to this repro.

https://github.com/what3words/magento1-w3w-plugin
https://github.com/what3words/magento2-w3w-plugin

**Comment by lemaryn** [comment]
Hi guys! 
Thank you for you quick feedback.
Regards,
Serhii
